# Data Processing

## 1. Import Libraries

In [1]:
import math
import numpy as np
import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

/tmp/ipykernel_11618/2596168336.py:4: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.set_option('future.no_silent_downcasting', True)

## 2. Load Original Data

In [2]:
PATH_PREFIX = "../"

In [3]:
data_tran = pd.read_json(PATH_PREFIX + "data/data_original/train.json")
data_test = pd.read_json(PATH_PREFIX + "data/data_original/test.json")

## 3. Data Preprocessing

### 3.1 Create the 'coauthors' column in training data

In [4]:
data_tran['authors_main'] = data_tran['authors'].apply(lambda x: [a for a in x if 0 <= a < 100])
data_tran['authors_coop'] = data_tran['authors'].apply(lambda x: [a for a in x if a >= 100])
data_tran['authors_main'] = data_tran['authors_main'].apply(lambda x: x if x else [-1])

In [5]:
data_test = data_test.rename(columns={'coauthors': 'authors_coop'})

### 3.2 Rename list format of text columns and combine them into a new column

In [6]:
data_tran = data_tran.rename(columns={'title': 'list_title', 'abstract': 'list_abstract'})
data_test = data_test.rename(columns={'title': 'list_title', 'abstract': 'list_abstract'})

In [7]:
data_tran["list_combined"] = data_tran["list_title"] + data_tran["list_abstract"]
data_test["list_combined"] = data_test["list_title"] + data_test["list_abstract"]

### 3.3 Create the string format of title & abstract and combine them into a new column

In [8]:
def list_to_string(lst):
    return ' '.join(map(str, lst))

In [9]:
data_tran['str_title'] = data_tran['list_title'].apply(list_to_string)
data_test['str_title'] = data_test['list_title'].apply(list_to_string)

data_tran['str_abstract'] = data_tran['list_abstract'].apply(list_to_string)
data_test['str_abstract'] = data_test['list_abstract'].apply(list_to_string)

In [10]:
data_tran['str_combined'] = (data_tran['str_title'] + ' ' + data_tran['str_abstract'])
data_test['str_combined'] = (data_test['str_title'] + ' ' + data_test['str_abstract'])

### 3.4 Fill NA in venue

In [11]:
data_tran['venue'] = data_tran['venue'].replace('', 465).fillna(465).astype(int)
data_test['venue'] = data_test['venue'].replace('', 465).fillna(465).astype(int)

## 4. Present the Preprocessed Data

### 4.1 Present Training Data

In [12]:
data_tran = data_tran[['authors', 'authors_main', 'authors_coop', 'venue', 'year', 'list_title', 'list_abstract', 'list_combined', 'str_title', 'str_abstract', 'str_combined']]
data_tran.head(5)

,authors,authors_main,authors_coop,venue,year,list_title,list_abstract,list_combined,str_title,str_abstract,str_combined
0,"[42, 13720, 36]","[42, 36]",[13720],20,9,"[41, 1550, 1563, 1594, 1544, 1919, 1644, 37, 1...","[2455, 1858, 2335, 1543, 1800, 1860, 2000, 286...","[41, 1550, 1563, 1594, 1544, 1919, 1644, 37, 1...",41 1550 1563 1594 1544 1919 1644 37 1539 1715 ...,2455 1858 2335 1543 1800 1860 2000 2867 1546 1...,41 1550 1563 1594 1544 1919 1644 37 1539 1715 ...
1,"[1359, 15881, 45]",[45],"[1359, 15881]",2,15,"[1731, 47, 11, 57, 4624, 1525, 1535, 47, 11, 3...","[40, 1542, 1691, 2449, 1535, 3616, 2206, 1904,...","[1731, 47, 11, 57, 4624, 1525, 1535, 47, 11, 3...",1731 47 11 57 4624 1525 1535 47 11 3522 2223 1653,40 1542 1691 2449 1535 3616 2206 1904 1642 154...,1731 47 11 57 4624 1525 1535 47 11 3522 2223 1...
2,"[19166, 17763]",[-1],"[19166, 17763]",465,17,"[2085, 1719, 1846, 1745, 2243, 1553, 1606, 159...","[40, 1542, 1691, 2449, 1535, 2610, 1543, 1535,...","[2085, 1719, 1846, 1745, 2243, 1553, 1606, 159...",2085 1719 1846 1745 2243 1553 1606 1596 42 41 ...,40 1542 1691 2449 1535 2610 1543 1535 1984 196...,2085 1719 1846 1745 2243 1553 1606 1596 42 41 ...
3,[97],[97],[],4,10,"[40, 1733, 1735, 1540, 1655, 46, 1624, 1547, 5...","[46, 1624, 1547, 56, 1687, 1644, 6, 7, 3386, 1...","[40, 1733, 1735, 1540, 1655, 46, 1624, 1547, 5...",40 1733 1735 1540 1655 46 1624 1547 56 1687 16...,46 1624 1547 56 1687 1644 6 7 3386 1542 2654 1...,40 1733 1735 1540 1655 46 1624 1547 56 1687 16...
4,"[19617, 2]",[2],[19617],9,10,"[38, 1592, 2088, 1543, 1574, 1727, 1597, 1813,...","[37, 3709, 3836, 1586, 2151, 1727, 3021, 1860,...","[38, 1592, 2088, 1543, 1574, 1727, 1597, 1813,...",38 1592 2088 1543 1574 1727 1597 1813 1926 152...,37 3709 3836 1586 2151 1727 3021 1860 1527 181...,38 1592 2088 1543 1574 1727 1597 1813 1926 152...

### 4.2 Present Testing Data

In [13]:
data_test = data_test[['authors_coop', 'venue', 'year', 'list_title', 'list_abstract', 'list_combined', 'str_title', 'str_abstract', 'str_combined']]
data_test.head(5)

,authors_coop,venue,year,list_title,list_abstract,list_combined,str_title,str_abstract,str_combined
0,"[16336, 1762, 4357, 12564]",223,19,"[3207, 24, 1798, 1738, 37, 2375, 1568, 11, 53,...","[37, 1662, 3207, 10, 33, 2037, 1738, 1642, 155...","[3207, 24, 1798, 1738, 37, 2375, 1568, 11, 53,...",3207 24 1798 1738 37 2375 1568 11 53 1584 1903...,37 1662 3207 10 33 2037 1738 1642 1553 4917 11...,3207 24 1798 1738 37 2375 1568 11 53 1584 1903...
1,"[21189, 14088]",223,19,"[40, 1560, 1536, 1544, 1609, 1705, 1658, 1543,...","[1731, 2130, 3674, 1705, 1656, 3077, 1546, 367...","[40, 1560, 1536, 1544, 1609, 1705, 1658, 1543,...",40 1560 1536 1544 1609 1705 1658 1543 52 11 33...,1731 2130 3674 1705 1656 3077 1546 3675 2051 2...,40 1560 1536 1544 1609 1705 1658 1543 52 11 33...
2,"[3625, 1198, 19889, 794, 2749, 7801]",7,19,"[47, 1574, 1729, 1641, 11, 37, 2533, 2015, 47,...","[1551, 1728, 3920, 1542, 1535, 1656, 1543, 153...","[47, 1574, 1729, 1641, 11, 37, 2533, 2015, 47,...",47 1574 1729 1641 11 37 2533 2015 47 1930 1549...,1551 1728 3920 1542 1535 1656 1543 1530 3053 2...,47 1574 1729 1641 11 37 2533 2015 47 1930 1549...
3,"[19810, 15173, 5876, 111]",21,19,"[1770, 53, 2054, 1549, 1529, 1723, 2796, 1547,...","[51, 1535, 2115, 1543, 1811, 1700, 1657, 1684,...","[1770, 53, 2054, 1549, 1529, 1723, 2796, 1547,...",1770 53 2054 1549 1529 1723 2796 1547 1543 47 ...,51 1535 2115 1543 1811 1700 1657 1684 1549 192...,1770 53 2054 1549 1529 1723 2796 1547 1543 47 ...
4,"[10932, 7668, 11907, 19601, 15307, 10492, 1049...",465,19,"[18, 1924, 23, 1544, 3927, 2686, 1543, 1535, 1...","[1775, 1746, 1842, 1525, 33, 2551, 1882, 1542,...","[18, 1924, 23, 1544, 3927, 2686, 1543, 1535, 1...",18 1924 23 1544 3927 2686 1543 1535 1660 1548 ...,1775 1746 1842 1525 33 2551 1882 1542 33 2548 ...,18 1924 23 1544 3927 2686 1543 1535 1660 1548 ...

## 5. Save the Preprocessed Data

### 5.1 Save the training and testing data as json

In [14]:
data_tran.to_json(PATH_PREFIX + 'data/data_processed/data_tran.json', orient='index')
data_test.to_json(PATH_PREFIX + 'data/data_processed/data_test.json', orient='index')

### 5.2 Save the label in onehot as npy

In [15]:
def process_label(data):
    
    n_author = 101  
    threshold_author = 100  

    author_list = np.zeros((len(data), n_author))

    for i, authors in enumerate(data["authors"]):
        author_id = np.array(authors)[np.array(authors) < threshold_author]
        
        if len(author_id) == 0:
            author_list[i, -1] = 1
        else:
            author_list[i, author_id] = 1

    return author_list

y_tran = process_label(data_tran)

np.save(PATH_PREFIX + 'data/data_feature/y_tran.npy', y_tran)